language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 7

cache:
  directories:
    - $HOME/.pnpm-store

before_install:
  - npm install -g pnpm
install:
  - pnpm install

after_success:
  - if [[ $TRAVIS_NODE_VERSION == "v4" ]]; then npm run coveralls; fi;
  - if [[ $TRAVIS_NODE_VERSION == "v4" ]]; then npm run semantic-release; fi;
