language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 8

before_install:
  - npm install -g pnpm
install:
  - pnpm install

after_success:
  - if [[ $TRAVIS_NODE_VERSION == "v8" ]]; then npm run coveralls; fi;
  - if [[ $TRAVIS_NODE_VERSION == "v8" ]]; then npm run semantic-release; fi;
